### ISSUE TITLE
Middleware not respecting Endpoint's `path` setting

### ISSUE THREAD

**Issue by cosmicboots** [zigzap/zap#119]
I'm not sure if this is a bug, but if not, it could stand to be better documented.

The `EndpointHandler` doesn't seem to respect the endpoint's path setting. This means that the endpoint's `.onRequest()` function gets called on every request, even if the request's path doesn't match the endpoint settings.

I would expect that `EndpointHandler` middlewares only effect requests with matching paths.

If this is a bug, I want to make sure the semantics for endpoint middleware paths are nailed down before I attempt to implement a fix. My initial assumption is a `startsWith()` check should occur here: https://github.com/zigzap/zap/blob/master/src/middleware.zig#L87.

**Comment by renerocksai** [comment]
I hacked together Middleware support and made the decision that it's probably good if handlers in the chain were path-agnostic for reusability. It's trivial to check for path match, and there can be different policies for what constitutes the relevant part of the path, especially in the case of reusing handler implementations in different contexts.

In my eyes, the whole point of a handler chain is so that anyone in the chain can take over. If you want to limit behavior, nothing stops you from deriving more strict handlers.

A `startswith()` implementation I find especially problematic considering having a giant nginx "config" doing url rewriting or port matching/dispatching for multiple zap apps on the same server, which was one of my major use-cases.

See the comment in the example. It is documented there:

https://github.com/zigzap/zap/blob/11fa66a31cf580189e01b0c353f0ccee16f90a0e/examples/middleware_with_endpoint/middleware_with_endpoint.zig#L123C1-L133C3

```zig
//
// !!!! ENDPOINT !!!
//
// We define an endpoint as we usually would.
// NO ROUTING IS PERFORMED
// as we are just going to wrap it in a bunch of Middleware components
// and therefore NOT using an endpoint listener that would the routing for us
//
// Hence, the endpoint should check r.path in its on_request to check wether
// it is adressed or not.
//
```

**Comment by cosmicboots** [comment]
Ah, I missed the comment about no routing from the example. I think it's worth adding a similar note to the doccomment for `EndpointHandler` just to be more explicit.

I can understand and respect the decision behind not performing routing for `EndpointHandler` by default; however, would it be worth exposing endpoint routing as an option for middleware? It could be as simple as adding an argument to to `EndpointHandler.init()` or making an `EndpointRouteHandler` type. 

Either way writing my own handler to be more strict is simple enough that I'll do that for the time being.

**Comment by renerocksai** [comment]
Yeah, you're right. If it's documented in the example, it's a clear sign that it's important information that should go into the docs. (At the time the example was created, it wasn't clear that autodoc would ever work for zap).

I think it's worth it, extending the EndpointHandler. I think having a struct of options passed to `init()`, where the route is an optional, is what I'd prefer.
