### ISSUE TITLE
Add ability to reuse address

### ISSUE THREAD

**Issue by dragosv** [zigzap/zap#130]
The http server allows to set reuse_address, would be beneficial to add it

**Comment by renerocksai** [comment]
Why do you suggest this? Have you ever run into reuse issues? I CTRL+C and restart all the time during development. 

The reason I am so puzzled, is: Zap (via facil.io) is setting the reuse socket option always, unconditionally, on server sockets. [link to source line](https://github.com/zigzap/zap/blob/29b923f96ee09d855b603866d2e149d506f72679/facil.io/lib/facil/fio.c#L2507)

**Comment by dragosv** [comment]
When starting multiple processes with zap the error I get is error: ListenError

zap: /root/.cache/zig/p/12209936c3333b53b53edcf453b1670babb9ae8c2197b1ca627c01e72670e20c1a21/src/zap.zig:350:13: 0x109125b in listen (zap)
zap:             return error.ListenError;

**Comment by dragosv** [comment]
@renerocksai the issue can be reproduced with a bash script that has

for i in $(seq 1 $(nproc --all)); do
  zap &
done

**Comment by renerocksai** [comment]
I pointed you to the line that sets `SO_REUSEADDR`, yet you still keep trying to make a point. I am on the fence whether you are just trolling, but for the benefit of the doubt:

Your example cannot work. You're starting multiple server processes listening to the same address and port, at the same time. Why would you want multiple servers listening to the same port? Have you thought this through? Where do you get this idea from? How is it supposed to work? Which process would receive connections / data? That is not what the `SO_REUSEADDR` option is for.

If you want multiple worker processes, set `.workers=n_workers` in the call to `zap.start`.

With the TCP protocol, `SO_REUSEADDR` allows for quick (re-) start of the listening process to an address that was previously in use (e.g. in `TIME_WAIT` state). However, if one instance of a server is already bound to the address and port, another instance cannot bind to the same address and port, **even if `SO_REUSEADDR` is set**.

On **UDP sockets** (different protocol, not used for http) multiple processes are allowed to bind to the same multicast/broadcast address and receive multicasts/broadcasts.

Try it with this python script if you still don't believe me. It does `server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)`.

```python
import socket
HOST='127.0.0.1'
PORT=5000

server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1) # enable address reuse
server.bind((HOST, PORT))
server.listen(5)
print(f"Server is running on {HOST}:{PORT}")
while True:
    connection,address = server.accept()
    req = connection.recv(1024).decode('utf-8')
    print(req)
```

**Comment by dragosv** [comment]
I was not trolling, this is how other frameworks work. I will use the workers settings instead.

**Comment by renerocksai** [comment]
Please show me one framework that can transcend the limits of TCP sockets and have multiple server processes listening to the same port. I am sorry but to me, this makes absolutely no sense. I am willing to learn though, that there may be frameworks that, e.g. bypass the operating system's TCP stack, and can do it.

Have you tried the python code?

**Comment by renerocksai** [comment]
To be clear. You said "The http server allows to set reuse_address, would be beneficial to add it". 

`reuse_address` is one of the [ListenOptions](https://ziglang.org/documentation/master/std/#std.net.Address.ListenOptions) of zig's `std.net.Address`, which has nothing to do with Zap. I thought it would be clear that Zap does not use zig's `std.http`.

I did some digging. Because, traditionally, features like `reuse_address` translated to the socket option `SO_REUSEADDR`, which has the limitations described above. Which you can also reproduce with the python script above.

However, more recently, an additional socket option has been introduced, which is also set in zig's standard lib, when `reuse_address == true`: `SO_REUSEPORT`. That one would allow (with conditions wrt security) to have multiple processes listening on the same port.

facil.io uses a reactor pattern that was typical pre-`SO_REUSEPORT` introduction, and does not require`SO_REUSEPORT`.

Since facil.io and zap manage worker processes, they are not meant for being started in multiple parallel instances. I am not keen on introducing `SO_REUSEPORT` into zap, because it would encourage a usage-pattern that works against the whole point of the framework.

But I can agree with you that nowadays it's possible to have multiple processes listening to the same port, thanks to `SO_REUSEPORT`.

**Comment by dragosv** [comment]
There are quite a few frameworks in various languages in the TechBenchmark (search for nproc in sh files). Does not mean it is something that zap should follow.

**Comment by dragosv** [comment]
@renerocksai On another note, Zap is now part of the TechBenchmark

https://www.techempower.com/benchmarks/#section=test&runid=235f2c13-5e49-44b8-9dc1-1d087d6353bc&hw=ph&test=db

Code:
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Zig/zap

Would appreciate suggestions for improving performance










https://www.techempower.com/benchmarks/#section=test&runid=235f2c13-5e49-44b8-9dc1-1d087d6353bc&hw=ph&test=db

Code:
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Zig/zap
