### ISSUE TITLE
HTML link files are not reloaded 

### ISSUE THREAD

**Issue by Satheeshsk369** [zigzap/zap#141]
```zig
fn on_request(r : zap.Request) void {
    r.sendFile("index.html") catch return;
}
```

This `index.html` file contains the link of `styles.css` and  `script.js` file ( I also mentioned the `.public ` folder having the above files). The html files perfectly reloaded but css and js files are not reloaded even though I rerun the server.  so I need to embed everything on html file. Is any option i have to watch those files?

**Comment by renerocksai** [comment]
There's no magic in zap. You need to set headers to non-caching.

LG, Rene
--
Rene Schallner
***@***.*** ***@***.***> / renerocks.ai
<https://renerocks.ai/>

On November 12, 2024, Rene Schallner ***@***.***> wrote:
> fn on_request(r : zap.Request) void { r.sendFile("index.html") catch
> return; }
> This index.html file contains the link of styles.css and script.js
> file ( I also mentioned the .public folder having the above files).
> The html files perfectly reloaded but css and js files are not
> reloaded even though I rerun the server. so I need to embed everything
> on html file. Is any option i have to watch those files?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/zigzap/zap/issues/141>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AHLWBJ3VODSOWPVPB36WB5T2AIDRJAVCNFSM6AAAAABRUEUSM6VHI2DSMVQWIX3LMV43ASLTON2WKOZSGY2TEMRZG43TMMI>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>

**Comment by renerocksai** [comment]
What I mean: your browser is caching th JS and CSS. It is not probably not even attempting to load them. Sending no-cache headers will force the browser to always attempt to load those files. Your setup is a bit strange in that you explicitly serve the index.html but leave all the other files to be caught by the public folder handling.

**Comment by renerocksai** [comment]
I did some research. If you look at zap's doc comments of `sendFile`:

```zig
/// Important: sets last-modified and cache-control headers with a max-age value of 1 hour!
/// You can override that by setting those headers yourself, e.g.: setHeader("Cache-Control", "no-cache")
```

The 1 hour is the default used in the facil.io library. If you use the public_folder feature, then all files in public_folder will be cached by your browser for 1 hour. There is no way to get around that without changing that sensible default in the C library.

If you need control over how your files are cached by browsers, serve them in your request handler, where you can set cache-control headers. (That's what I always do, I hardly ever use the public_folder feature).

Alternatively, disable caching in your browser while developing  & changing assets frequently.
