### ISSUE TITLE
Zig as a starter 

### ISSUE THREAD

**Issue by Kinfe123** [zigzap/zap#76]
Just simple zig build file that we can build an app on top of like the starter file which we could get zap on a fly for my project

**Comment by renerocksai** [comment]
Did you read the README?

There is a build.zig.zon and an example for what to do in your build.zig, after you have run zig init-exe.

I want to close but maybe I don't get your question. If so, please elaborate in full sentences.

**Comment by Kinfe123** [comment]
Yeah yeeah there is man.. but it the reaadme is too much so that might be cool on dx side.. thats why no worries man ;)

**Comment by renerocksai** [comment]
Please make a more concrete suggestion. Zig creates the build.zig for you, you only have to paste in 2 lines. 

To be honest, I am thinking that if that's too much hassle, one is probably better off trying something else.

DX 🤣: "I want to dev but put ZERO effort into it"

Where would we even put the extra file and how should people looking for "DX" find it? Plus, they'd need the zon file, too. I might be stupid but if I even parse you correctly, what I think you want doesn't sound thought through well.

I value my time, too. Maybe the best way forward is you submit a PR.

**Comment by Kinfe123** [comment]
hmm.. you got a point but the reason i raised is because of i just told my friend about this means zap for building web servers yeah but i really send the link to this github repo and he was confused to where it starts thats why i guess it needs a prior xp on setting up stuff for local dev and playing around with sys lang makes the hassle little bit less :) .... personally does not have a problem but he was kind of heck confused to start off but yeah what i suggested to paste the code from build.zig or build.zon.zig. .. You are absolutely correct but people get reffered to this might be interested on some mini things that they could narrow there scope like just fork and get to the point.. idk but for me it is fine .

**Comment by renerocksai** [comment]
Aaaaah, got you! Maybe point your friend further down in the readme: https://github.com/zigzap/zap#getting-started

Further down it shows how to create a zig project and add zap in easy steps. 

The only easier alternative I can think of is creating a sample project that others can just fork. Updating that for every release is a bit of extra work. I have one for zig master, so yeah, maybe making an official one and linking to it in a prominent place would help.

**Comment by Kinfe123** [comment]
yep man that is what i am saying... you got me...that would be too nice

**Comment by Froxcey** [comment]
I think it would be nice to have a [template repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository) for creating a Zap application, many other backend projects has the same thing.

<img src="https://github.com/Avdan-OS/Compositor/assets/51555391/d0379882-f2dc-42e1-962f-b3f122db656f" alt="vibe" width="60"/>

**Comment by Kinfe123** [comment]
@renerocksai If you want zap starter template for custom or from scratch projects you can use my template here - https://github.com/Kinfe123/zap-zig-starter

**Comment by Kinfe123** [comment]
@renerocksai  shall i contribute this on main branch the above starter ... which can pushed on you branch

**Comment by renerocksai** [comment]
What do you mean with pushing to main repo branch? That doesn't make sense to me.

To be git-clonable, the "starter project" should be its own repo, e.g.: `zigzap/hello`.

I would clean up your template:

- explain what it actually **does** (e.g. when it runs)
- since it also serves a public folder, this folder should exist and contain at least something.
- it should be made clear that the public folder content takes precedence over the callback (avoid surprises!)
- it should start only one worker or else people will shoot themselves in the foot trying to share state
- remove the stupid test
- at least mention `zig build run` 

None of the above is hard. Creating such a starter template probably takes only a few minutes.

The more complicated part is: keeping it up-to-date with zap releases (build.zig.zon). Can that be done easily, ideally in a GH action when rolling a release? I guess the easiest option is to have a daily GH workflow that clone zap master, checks for zon changes in the README of zap, and commits a zon update to the starter. Then a second GH workflow that checks if it still builds with the latest zon update - so I get at least notified when the starter gets broken by a zap release.

Instead of parsing the README, I could also update zap's release workflow to update a json file that can easily be curled from the starter template workflow. 

I don't hace time ATM but that's what I'm thinking about.

**Comment by Kinfe123** [comment]
yeah i am basing my thought based on the templating stuff that mention and yeah it was also thinking syncing up using GH that can checkout to the master ..

**Comment by Kinfe123** [comment]
yeah gotta you your clean up .. since i am introducing it to the public i just get the fresh copy of zig init and start adding necessary files to make sure it works but as you said it needs really a clean up that to make sure it actually makes sense

**Comment by renerocksai** [comment]
for now maybe https://github.com/zigzap/hello-world will do
